os: linux
dist: bionic

language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories:
    - node_modules
    - static/doc/typedoc # Cache generated typescript documentation

jobs: 
  include:
    - stage: "Static Analysis"
      name: "Eslint"
      script: npm run eslint
    - script: npm audit
      name: "Audit"
    - stage: "Build"
      script: npm run tsc
    - stage: "Test"
      name: "Unit Tests"
      script: npm run unitTest
    - script: npm run integrationTest
      name: "Integration Tests"
    - stage: "Generate typedoc"
      script: npm run typedoc
    - stage: "Compare version and tag"
      script: if [[ $TRAVIS_TAG =~ $( cat ./package.json | jq '.version' | cut -d'"' -f2 )$ ]]; then exit 0; else exit 1; fi
    - stage: "Deploy"
      script: bash scripts/ci-dep.sh

stages:
  - "Static Analysis"
  - "Build"
  - "Test"
  - "Generate typedoc"
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/