os: linux
dist: bionic

language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories:
    - node_modules
    - static/doc/typedoc # Cache generated typescript documentation

services:
- postgresql

before_script:
  # Install postgres, create test user and test database for integration tests
- sudo -u postgres createuser groupcarapitest
- sudo -u postgres psql -c "CREATE DATABASE groupcartest WITH OWNER groupcarapitest;"

jobs: 
  include:
    # Jobs for static analysis
    - stage: "Static Analysis"
      name: "Eslint"
      script: npm run eslint
    - script: npm audit
      name: "Audit"

    # Building job
    - stage: "Build"
      script: npm run tsc

    # Testing jobs
    - stage: "Test"
      name: "Unit Tests"
      script: npm run unitTest
    - script: npm run integrationTest
      env:
      - NODE_ENV=test
      name: "Integration Tests"

    # Jobs for generating documentation
    - stage: "Generate typedoc"
      script: npm run typedoc

      # Deploy jobs
    - stage: "Deploy Development"
      script: bash scripts/deploy_dev.sh
    - stage: "Deploy Beta"
      script: bash scripts/deploy_beta.sh
    - stage: "Compare version and tag"
      script: if [[ $TRAVIS_TAG =~ $( cat ./package.json | jq '.version' | cut -d'"' -f2 )$ ]]; then exit 0; else exit 1; fi
    - stage: "Deploy Release"
      script: bash scripts/deploy_release.sh

# Define stages
stages:
  - "Static Analysis"
  - "Build"
  - "Test"
  - "Generate typedoc"
  - name: "Deploy Development"
    if: NOT tag IS present AND type = push AND fork = false AND branch = develop
  - name: "Deploy Beta"
    if: NOT tag IS present AND type = push AND fork = false AND branch = master
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy Release"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/