os: linux
dist: bionic

language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories:
    - node_modules
    - static/doc/typedoc # Cache generated typescript documentation
  yarn: true

services:
- postgresql

install:
- sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
- npm_config_build_from_source=true yarn add canvas
- yarn install

before_script:
  # Install postgres, create test user and test database for integration tests
- cd ~postgres/
- sudo -u postgres createuser groupcarapitest
- sudo -u postgres psql -c "CREATE DATABASE groupcartest WITH OWNER groupcarapitest;"
- cd ~travis/build/Ratsch0k/group-car-api

jobs:
  include:
    # Jobs for static analysis
    #- stage: "Static Analysis"
    #  name: "Eslint"
    #  script: yarn eslint
    #- script: yarn audit
    #  name: "Audit"

     # Building job
    #- stage: "Build"
    #  script: yarn tsc

     # Testing jobs
    - stage: "Test"
    #  name: "Unit Tests"
    #  script: yarn test:unit
      script: yarn test:integration
      env:
      - NODE_ENV=test
      - DEBUG=group-car*
      name: "Integration Tests"

      # Deploy jobs
    - stage: "Deploy Development"
      script: bash scripts/deploy_dev.sh
    - stage: "Deploy Beta"
      script: bash scripts/deploy_beta.sh
    - stage: "Compare version and tag"
      script: if [[ $TRAVIS_TAG =~ $( cat ./package.json | jq '.version' | cut -d'"' -f2 )$ ]]; then exit 0; else exit 1; fi
    - stage: "Deploy Release"
      script: bash scripts/deploy_release.sh

# Define stages
stages:
  #- "Static Analysis"
  #- "Build"
  - "Test"
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-alpha(.\d+)*$/
  - name: "Deploy Development"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-alpha(.\d+)*$/
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-beta(.\d+)*$/
  - name: "Deploy Beta"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-beta(.\d+)*$/
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy Release"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/