os: linux
dist: bionic

language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories:
    - node_modules

jobs: 
  include:
    - stage: "Static Analysis"
      name: "Eslint"
      script: npm run eslint
    - script: npm audit
      name: "Audit"
# Tests don't exist yet
#    - stage: "Test"
#      script: npm test
    - stage: "Deploy"
      script: _scripts/ci-dep.sh

stages:
  - "Static Analysis"
  - name: "Deploy"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/