version: "3.9"

services:
  postgres:
    container_name: group-car-db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=groupcartest
      - POSTGRES_PASSWORD=groupcartest
      - POSTGRES_USER=groupcartest
    ports:
      - '5432:5432'