version: "3.9"

services: 
  group-car:
    container_name: group-car
    build: .
    ports:
      - $PORT:8080
    volumes: 
      - $FRONTEND_PATH:/home/node/group-car-api/static
    env_file: 
      - $SERVER_ENV_FILE_PATH
    working_dir: /home/node/group-car-api
    restart: always
    command: /bin/bash -c "yarn sequelize-cli db:migrate && node -r tsconfig-paths/register ./build/group-car.js"