openapi: 3.0.3
info:
  title: Group car api
  version: 0.1.0

# Paths
paths:
  /api/status:
    get:
      summary: Test path
      description: A test path to check if the server is reachable
      responses:
        200:
          description: The standard response. The server is reachable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusObject'
  /api/users:
    get:
      summary: Get all users
      description: Get a list of all users
      responses:
        200:
          description: The list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
# Components
components:
  schemas:
    # Status schemas
    StatusObject:
      type: object
      properties:
        server:
          $ref: '#/components/schemas/StatusType'
        database:
          $ref: '#/components/schemas/StatusType'
    StatusType:
      type: string
      enum:
      - 'up'
      - 'down'
    # User schemas
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        isBetaUser:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'

# External docs
externalDocs:
  description: Code documentation is here
  url: /doc/typedoc