openapi: 3.0.3
info:
  title: Group car api
  version: 0.1.11
  
tags:
- name: Authentication
  description: Requests for authentication

# Paths
paths:
  /api/status:
    get:
      summary: Test path
      description: A test path to check if the server is reachable
      responses:
        200:
          description: The standard response. The server is reachable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusObject'
  /api/user:
    get:
      summary: Get all users
      description: Get a list of all users
      responses:
        200:
          description: The list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
  
  # Authentication
  /auth/login:
    put:
      summary: Log in
      description: Logs the user in with the given username and the given password
      tags:
      - Authentication
      requestBody:
        description: Login data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginObject'
      responses:
        200:
          description: The login was successful
        400:
          description: The login request is malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestError'
        501:
          description: The endpoint is not yet implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestError'
  /auth/sign-up:
    put:
      summary: Sign up
      description: Signs the user up with the given attributes
      tags:
      - Authentication
      requestBody:
        description: The sign up properties
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpObject'
      responses:
        201:
          description: The user was successfully signed up
        400:
          description: The request is malformed, the request is missing parameters or parameters are invalid, or a user with the given username already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestError'
# Components
components:
  schemas:
    # Status
    StatusObject:
      type: object
      properties:
        server:
          $ref: '#/components/schemas/StatusType'
        database:
          $ref: '#/components/schemas/StatusType'
    StatusType:
      type: string
      enum:
      - 'up'
      - 'down'
    # User
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        isBetaUser:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    # Authentication
    LoginObject:
      type: object
      properties:
        username:
          type: string
        password: 
          type: string
    SignUpObject:
      type: object
      properties:
        email: 
          type: string
        username:
          type: string
        password:
          type: string
      example:
        email: demo@mai.com
        username: demo
        password: 123456
    # Error
    RestError:
      type: object
      required: 
      - status
      - statusCode
      - timestamp
      - message
      properties:
        status:
          type: string
        statusCode:
          type: number
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        detail:
          type: object

# External docs
externalDocs:
  description: Code documentation is here
  url: /doc/typedoc