name: WIP
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_MERGE_PAL }}
    steps:
      - uses: wip/action@v1.0.0
